title:              CoVprehension
email:              covprehension@gmail.com
description:        Comprendre l'épidémie actuelle de COVID-19<br>Une question, un modèle
author:             Le collectif CoVprehension
baseurl:            "/"
url:                "https://covprehension.org"

# Social Profiles
twitter_username:   
github_username:    covprehension
facebook_username:  
linkedin_username:  
rss_link:           https://covprehension.org/feed.xml
question_form_link: https://framaforms.org/covprehension-mettez-nous-au-defi-posez-vos-questions-1585223922

## Add your google-analytics ID here to activate google analytics
#google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap 
